---
title: Speaking notes
output: word_document
---

Really want to stress, you have a comment or question, literally just jump in
and ask. No need for raising hands, though you can if you want to.

## 6.

I want you to go over the next 5 slides (each of the budget tables). Look them
over, think about them, and once you've done that, let's hear your thoughts on them.

## 12.

what would, or maybe do?, you do for budgeting, how would you strategize
making sure you can survive?

## 13.

(briefly describe figure)

## 17.

If you remember from last class, there are limitations to measuring dietary
intake in kids (confirm with Sarah)

## 18.

Just like before with the budget tables, I want you to look over these figures
on the next 5 slides, up to the beverage figure. Then we'll discuss things you
noticed or thought about, or general comments.

## 23.

Female protein inadequacy tends to be higher. Notice the male inadequacy for
19-30 in food secure households.. non-existent! As in they get all the protein
they need.

## 24.

Total fat intake... What's the problem with this measure though? What is it
telling us?

Also, getting too low may be a problem...

## 25.

Surprisingly.. I would have assumed higher processed, cheap foods would be
bought, and so higher sodium. But we're missing something here... There is only
one category for food insecure... So there might be differences, but it would
not be picked up here.

## 27.

Can you guess what nutrient adequacy would be for kids? Well, for very young
kids.

## 33.

what would you anticipate seeing? for disease and food insecurity? After
what we talked about

## 35.

It's a well known observation that males tend to have higher rates of diabetes,
tho in the general public, females tend to have higher CVD rates. Interesting
about the higher rates of mood or anxiety disorders. I have no expertise in this
area, does any one have any idea why? I'm just curious...

## 36.

Inuit have a unique situation for those in food insecure homes. ie. no hunter.
But what about this here? Fewer vegetables. Is that really surprising or even a
bad thing? Marker of something else? aka, SES

We also don't have solid evidence to really say what a healthy diet is for the
Inuit... Almost all of the research done on healthy eating has been on
Europeans, mainly.

## 38.

We've already gone over this, but just to re-iterate, what are the possible
mechanisms so far?

## 39.

Remember last class I mentioned about obesity and lower income? There was a
caveat to that...

## 40.

(describe figure)

## 45. 

So what's going on? Why is there this discrepancy between perception and
reality for obesity and food insecurity? Why doesn't obesity track with food
insecurity?
