---
title: Speaking notes
output: word_document
---

## 1:

 Big picture, because of proximity to the US, who are very individualistic
and capitalistic, we get influenced. Canada is in an interesting position
because of our history and influence from Europe. So while Canadian society is
individualistic, we have an aspect of socialism which makes us a much more
'collectivistic'/socialistic than the US. So in this context, that when you're
'learning about food insecurity try very hard to draw on that social/collective
'aspect... it is public health nutrition, not individual health nutrition. 

## 3:

 before we get into food insecurity, we have to identify why it matters, why
it's important. 

 Outside of the role that food has on health, it is a fundamental human
right that has been enshrined in many international legal frameworks 

## 6:

 pause here, is hunger different from food insecurity? Why? 

## 9:

 Qualitative food selection 
 Quantitative in food intake, hunger 

## 10:

 there's no right answer here, but why might it be important to measure the
experience of food secure compared to a more 'objective' measure like body
composition or nutrient status? 

## 11:

 Personal story about cousin 

## 13:

 we often compare to the US, and in this case we differ slightly. US and Can
use the same method to measure food insecurity (ie the same questionnaire), but
they have a different definition. 

 While the US has language that includes marginal food insecurity, their 
methods haven't changed and they still use these categories 

## 14:

 Health canada has a marginal category, but it is classed with food secure.

## 15:

 Thoughts? do you think it's reasonable to include this level? 

## 17:

 Question: outside of the questions themselves, how accurate do you think
the HFSSM is at determining food insecurity

## 23:


 remember how I said that the US has a different definition of food
insecurity? 

 US uses different definition, so if we use their definitions, there are
differences in our rates. Which is a bit frightening for the US situation, as
that means they probably have a lot more potential food insecurity than they are
reporting... Either that or we are overestimating... But what do you all think?
Do you think Canada's approach is reasonable? Or is the US definition better?

 this doesn't include marginal 

## 24:

 Think about that prevalence rate in Nunavut. Any thoughts on why that is?
How did they traditionally get their food? So westernization, yea it's a big
problem, it's the bad guy, making them more sedentary, more reliant on so called
'market foods'... but let's think back to their traditional diet... Many of them
still consume that type of diet... Let's think even bigger picture, what other
reasons might there be for the food insecurity (hint climate change). Think also
to how they evolved in the north, how they evolved to the food available... do
you think they will just as healthy as you or I in eating a 'western' diet?
Whether it is healthy or not? 

 High rates in Nunavut, maybe because Nunavut reflects the First Nations and
Inuit overall, since the CCHS doesn't collect from reserves 

## 25:

 what do you think is going to happen to those children who grow up
experiencing food insecurity? And to their children's children? Keep in mind the
role that maternal diet and environment plays in a developing fetus and baby

## 27:

 historical context of food insecurity in Nunavut (colonization). If you
were to create an intervention, you would need to consider the role that
Europeans have played in getting them to that place to begin with 

## 29:

 any interesting thoughts on this figure? 

## 33:


 Why do you think so? Thoughts ideas? What's going on here? 

## 34:

 if you were to make guesses, what would be some predictors? We already know
being First Nations is a very strong predictor of being food insecure, but what
about others?

## 38:

 remember how low senior citizens were to food insecurity? Any thoughts on
why? 
